(ready) Scaling dungeon visible area. Has enhanced xBRZ scaling and custom window size too. (#331)
* First step: moved Attnam eclipse project files to '.devsPrefs/Attnam/'

* ######
## Eclipse developers preferences over different operational systems
## and personalized configurations.
######

# link to some user folder at /.devsPrefs
/.devsPrefs/Current

# direct links to preferences at /.devsPrefs/Current
/.cproject
/.project
/.settings

# Git ignore files are special. They are relative to their current path!
# If the one at '/.devsPrefs/SomeUserName/.gitignore' remains named like that,
# git will recognize and ignore files as that sub folder is a root folder!
# Therefore ONLY that file must be named like: '/.devsPrefs/SomeUserName/.gitignore.SomeUserName'
# And after creating the link to it, the link itself must be renamed to '.gitignore' to be again recognized by git.
/.gitignore

* added script to automate symlinks creations on linux: prepareUser.sh

* prepareUser.sh: improved msg.

* still studying enhanced scaling possibilities.

* initial simple test directly from the doublebuffer worked!

* (still buggy)
custom full dungeon scaling (from 2 to 6) working well but a bit slow.
still too much memory hungry! needs fixing...
changing dungeon scaling option in game is messy if not in full screen mode.
Obs.: beware full screen mode tho, may be hard to get to other apps if the memory is swapping..

* look mode zoom xbrz stretch now can be independent of everything else.

* trying to prevent memory hungry scaling  thru xbrz,
SurfaceCache is working but not preventing that yet...

* now caching sdl surfaces and uint32 arrays, the performance and memory usage improved a lot!

* minor fixes concerning xbrz lib internal cache

* fixed wrong full window scaling during dungeon only scale in-game option.

* allowed increasing the window width and height

* increased window width and height now also shows increased dungeon visible area

* fixed text messages history log width

* before tracking again xbrz slowdown

* allowing stretched regions to be updated:WIP

* it now can xbrz only around the player a few squares, and it is... extremelly fast!!!
TODO: going to create option for how many squares around.

* WIP: squares around player just require limits to not crash near edges, 0 for now.

* WIP: squares around player protected against crash at upper left dungeon corner.

* Done: squares around player working great at all 4 dungeon corners!

* trying to fix the final alignment of the xbrz just around the player.

* Fixed correct positioning of xbrz scaled just around player, for best performance.

* fixed (expectedly) execinfo.h compile error for win32

* Put execinfo under UNIX check

* execinfo properly this time

* dungeon area now has tiny border at least.
I think now execinfo.h will be fixed.

* removed execinfo.h requirement

* WIP: preparing some code for scaled xbrz for each square.

* scale xbrz: fixed crash when starting a new game (about 0 sized stretch blit)

* positioned dialogs and scaled dungeon better during dungeon scaled mode

* fixed to "xBRZ" where it can be read.
fixed sfx to match more for: .*difficult for you.*

* fixed: stretched dungeon over new game initialization animation
fixed: stretched dungeon over after death animation

* xbrz stretch/scale: when inventory, equipmenu and opened container are activated, Silhouette and equipped items will be scaled up, this wont compete with dungeon scale up for CPU.

* let user configure silhouette&eqpdItems scale

* LookZoom factor increased from 5 to 6 (xbrz limit).
WIP: when browsing items on lists, the currently highlighted will show a scale up image at same place the LookZoom mode uses.

* Done: when browsing items on lists, the currently highlighted will show a scale up image at same place the LookZoom mode uses.

* WIP: alternative scaled up list items positioning;
added some debug macros enabled thru -DDBGMSG;

* new file: FeLib/Include/dbgmsg.h

* DONE: alternate scaled up list item positining feature.

* removed not required dbgmsg.h

* properly cleared macro defs when DBGMSG is not defined

* added macro eraser for non required dbgmsg.h

* Added option to set the width of item's list so the user can decide the best fitting for it balanced with the silhouette&eqpdItems scaled up.

* added 'throw' command to list item zoom;
alt list item width only if silhouette is scaled up;

* Commenting out debug macros to let travisci work.

* Commenting out debug macros to let travisci work.

* Trying to fix travisci for ivanWin.

These methods should be 'inline', but travisci ivanWin final linking is
failing with: "undefined reference to" it.

If it fails again, I will revert to inline, as it shouldnt(?) be a problem,
as it compiles on all other tests...

* added 'open' command to list item zoom capability;

* Added some pre-work to one day import and export bitmaps individually for each thing.
Re-enabling debug messages.
Testing if travisci will compile it all with new dbgmsg macro eraser.

* fixed main menu background for window size > 800x600

* Fixed inventory list width if silhouette scaleup is active.

* cleaning and clarifying the code a bit

* fixed main menu background glitch when coming back from cfg option

* lists now wait for keyUp event when pressing Enter or some direct option, not on Down or Up keys (for fast browsing)

* Up and down now use generic WaitForKeyEvent(i).
Fixed outlined weared cloak that only showed black dots.

* fixed some text visibility problems;
drawed rectangle around, for look zoom;

* new method for reuse: graphics::DrawRectangleOutlineAround()

* fixed list item alt pos to be generic;
made the code more clear to read about game::SetStandardListAttributes(l);
felist.cpp: fixed (new) empty wait loop for travisci?;

* b4 letting felist object draw the alt list item pos;

* WIP: felist draws the altPos list item;

* WIP: felist draws the altPos list item;

* WIP: felist draws the altPos list item;

* DONE: felist draws the altPos list item;

* disabled xBRZ around player (this code may change) in look zoom mode for now

* fixed player name visibility;
fixed look zoom message visibility;

* b4 fixing "background" for felist

* fixed config text cleanup;
allowed outline for any stretch region;
outline for stretched silhouette;
made private some exposed graphics:: fields;
WIP: trying to fix dungeon drawn below felist;
WIP: trying to fix dungeon stretch over busy animation;

* WIP: reworking when stretched dungeon should be denied;

* WIP: reworking when stretched dungeon should be denied;

* WIP: reworking when stretched dungeon should be denied;

* DONE: reworking when stretched dungeon should be denied;

* WIP: trying to improve visuals when felist is drawn;

* WIP: trying to improve visuals when felist is drawn;

* WIP: trying to improve visuals when felist is drawn;

* WIP: trying to improve visuals when felist is drawn (3rd try);

* WIP: trying to improve visuals when felist is drawn, 5th try.

* DONE: trying to improve visuals when felist is drawn.

* Fixed felist crash.
.cproject: I found no define for LINUX only for UNIX.

* dummy commit to let travisci retry after failing downloading something
(that could be on some cache locally...):
https://travis-ci.org/Attnam/ivan/jobs/362360675

* added compatibility defines for xbrzlib

* libxbrz improving cache management

* libxbrz: fixed error messages.

* fixed outline blinking

* improved list item alt pos (by disabling the full background for it, but the code is still there if someone want it back)

* WIP: reorganizing, simplifying and improving user options quality:
DONE - in-game togglable xBRZ for everything, no need to restart.

* WIP: reorganizing, simplifying and improving user options quality:
DONE - sorted and changed description of some of the new options.

* WIP: reorganizing, simplifying and improving user options quality:
DONE - let options that require restart actually work like that.

* Full dungeon can now be xBRZ to the static cache that is fastly drawn before felist page.

* fixed wrong trasparent dots when xBRZ stretching the silhouette

* libxbrzscale: improved inline define readability.
Added many more commands to when silhouette streching is enabled.

* WIP: ClearNonVisibleSquaresAroundPlayer

* WIP: ClearNonVisibleSquaresAroundPlayer

* WIP: ClearNonVisibleSquaresAroundPlayer

* DONE: ClearNonVisibleSquaresAroundPlayer
Fixed bitmap::StretchBlitXbrz to consider maskcolor;

* When a list of items is opened, will only use xBRZ on the full dungeon
if it was already doing that (user opted for 0 squares around player)
before opening it.

* fixed missing rm for DBGBLD

* fixed wrong rm for DBGBLD

* fixing crash when PrepareToClearNonVisibleSquaresAroundPlayer() is out of dungeon limits

* cleaning the code a bit

* fixing PrepareToClearNonVisibleSquaresAroundPlayer

* WIP: fixing PrepareToClearNonVisibleSquaresAroundPlayer

* DONE: fixing PrepareToClearNonVisibleSquaresAroundPlayer()

* CanBeFeltByPlayer now works at PrepareToClearNonVisibleSquaresAroundPlayer

* WIP: Improving "around player" code.
WIP: Joining logic from UpdatePlayerOnScreenBlitdata() and PrepareToClearNonVisibleSquaresAroundPlayer().
Added detailed explanations to some of what was coded to easy maintenance later.
Fixed bug when on wilderness.
Globalized optional dbgmsg for easy reuse.

* Fixed small animated squares being drawn while felist is active.
reworked dbgmsg to be less intrusive.

* On death: prevent xBRZ, shows silhouette with items, allows seeing 'zoomed monsters' massacre;
Added optional alternative death reviewer from ivan3D, where we can spend more time reviewing things b4 exiting;

* Improving death reviewer related to xBRZ zoom, alt mode and it's keys.

* WIP: rework into one method: PrepareToClearNonVisibleSquaresAroundPlayer()+UpdatePlayerOnScreenBlitdata() to simplify its understanding (if possible).

* Added experimental optional code to improve controls responsiveness
due to extremely low fps in full dungeon xBRZ mode (around player = 0).

* Added experimental automatic frameskip option.

* snore sounds

* fall down sound

* fixed: stretched blit active on main menu while configuring things;

* go travisci go...

* Frame skip for stand-by animation seems to be working well.
Added option to skip it all until a key is pressed: FrameSkip=-2.

* added option to show full dungeon name.

* Had to remove config.txt as it was causing some conflicts
preventing fixes/updates at SoundEffects.cfg.

* GoTravisciGo...

* look mode now has xBRZ around look spot;
new option: always center on player after exiting look mode;
configured a few new sfx regex;

* minor adjustments to look mode with xBRZ around look spot;

* Felist waitKeyUp code is pre-processor optional now, as I believe it is only required on linux;

* pre-processor FELIST_WAITKEYUP

* Preparing to split some other changes to simpler pull requests.

* Configured a few new sfx regex;
Had to remove config.txt as it was causing some conflicts preventing fixes/updates at SoundEffects.cfg;
New fall down and snore sounds;
Renamed intro2.wav to Woo-Hoo.wav
Renamed and moved ivanSndDebug.txt to home path.

* Added optional alternative death reviewer from ivan3D, where we can spend more time reviewing things before exiting;
Grouping config options by context (as with new xBRZ options from the other branch this will help a lot);
Added developer config duplicity check helper.

* added install instructions for FELIST_WAITKEYUP

* WIP: improving lookzoom mode.

* Adjusted "xBRZ around" to be disabled after death and in lookZoom in dark areas (for now).

* Added developer config duplicity check helper.

* option to show full dungeon name (would still be good to be prettified tho..)

* Frame skip for stand-by animation on slow machines or during CPU heavy load.
Added option to skip all stand-by animation frames until a key is pressed: FrameSkip=-2.

* restoring main branch .project, .gitignore, .cproject files,
as the optional ones are easy to apply with a single command
(on linux at least).

* NEWS file

* Grouped config options in categories.

* rearranged config options a bit (I think it could be better tho, one day...)

* fixed "xBRZ around" glitch while typing answer on a string question.

* added pray cmd to zoomed list item

* Fixed "xBRZ around" glitch showing while in config menu when typing numbers;
Added custom optional entries stack length (inventory, drop, throw etc).

* Full dungeon name now shows the level in roman numbers.
Obs.: the full dungeon name seems to be stored on the savegame,
so only new games (actually new dungeon instances) will show the updated
ones from the .dat dungeon files.

* Removed all unfriendly assert code in favor of user friendly ABORT macro;

Moved stacktrace code to error.cpp to be more useful.
Non WIN32 only as it was already.
(A WIN32 alternative would be good too to let users help us more easily);

WIP: Adding current position mouse zoom feature;

* WIP: Adding current position mouse zoom feature;

* WIP: Adding current position mouse zoom feature;

* moved WIP:mouseZoom to other branch..

* FinalFixes:

Removed all unfriendly assert code in favor of user friendly ABORT macro;

Moved stacktrace code to error.cpp to be more useful.
Non WIN32 only, as it was already.
(A WIN32 alternative would be good too to let users help us more easily);

* fix for error.cpp (no pun intended)

* FIXED: instead of zoomMode it now checks for positionQuestionMode
to determine usage of "xBRZ around". This makes it not glitch during
a "teleport to" question.

* Stretched list item can now be fully disabled.